juntos-com-vc/juntos.com.vc

db/migrate/20160126164015_add_recurring_to_channels.rb, db/migrate/20160126171627_create_recurring_contributions.rb, db/migrate/20160126171726_add_recurring_contribution_to_contributions.rb
* Creates a `recurring_contributions` table to store the data from
recurring donations;
* Adds a boolean field to `channels` to make it recurring or not;
* Adds a reference to a recurring contribution in `contributions` table.
=> Update the database to add recurring contributions

app/views/juntos_bootstrap/projects/contributions/edit.html.slim
The neighborhood field can't be blank while creating a contribution
=> Make neighborhood a required field to contribution

lib/tasks/deploy.rake
Change the default host to https://git.heroku.com in order to push
correctly.
=> Fix deploy task

Gemfile, Gemfile.lock, config/routes.rb
Only admin users will be able to view the monitor page
=> Add Sidekiq monitor

app/assets/javascripts/app/project_form.js, app/controllers/projects_controller.rb, app/models/project.rb, app/models/project_partner.rb, app/policies/project_partner_policy.rb, app/policies/project_policy.rb, app/views/juntos_bootstrap/projects/_dashboard_project.html.slim, app/views/juntos_bootstrap/projects/image_thumbs/_partner_thumb.html.slim, app/views/juntos_bootstrap/projects/templates/_partner_card_template.html.slim, app/workers/project_partner_process_worker.rb, db/migrate/20160328170555_add_images_fields_to_project_partners.rb, spec/factories.rb, spec/models/project_partner_spec.rb, spec/models/project_spec.rb, spec/workers/project_partner_process_worker_spec.rb
In order to avoid timeouts on Heroku, this PR:
* Uploads project partners images directly to Amazon S3;
* Process the images on background via a Sidekiq worker.
=> Upload project partners images directly to S3

app/assets/javascripts/app/project/project_cover_uploader.js, app/assets/javascripts/app/project_form.js, app/views/projects/_project.html.slim
Display a preview of the uploaded image in the project box next to the
uploaders in project dashboard.
=> Preview cover image in a box on project dashboard

app/models/user.rb, app/services/user/update_users_staffs_service.rb, db/migrate/20160420155100_add_staffs_to_users.rb, lib/tasks/update_users_staffs.rake, spec/services/user/update_users_staffs_service.rb, spec/tasks/update_users_staffs_rake_spec.rb
We're going to permit a user to belong to multiple teams, to do so we need
a way to store multiple staffs in a user record
=> Change users' staffs to be an array

app/controllers/users_controller.rb, app/controllers/who_we_are_controller.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/juntos_bootstrap/who_we_are/show.html.slim, app/views/users/_current_user_fields.html.slim, app/views/users/_project.html.slim, config/locales/catarse_bootstrap/views/pages/who_we_are.pt.yml, spec/controllers/who_we_are_controller_spec.rb, spec/factories.rb, spec/models/user_spec.rb
It was necessary to update the existing records as seen on #127
=> Allow users to belong to more than one staff group

config/database.sample.yml
Our dump files are still using Catarse's database name :disappointed:
=> Update database names on database.sample.yml

app/views/juntos_bootstrap/projects/contributions/edit.html.slim
=> Recurring form fixed

app/views/juntos_bootstrap/projects/contributions/edit.html.slim
Reverts juntos-com-vc/juntos.com.vc#138
=> Revert "Recurring form fixed"

app/views/juntos_bootstrap/projects/_project_header.html.slim, app/views/juntos_bootstrap/projects/show.html.slim
Texto com o status do projeto amigosdobem removido
=> Don't show amigosdobem on contribution display status

app/controllers/users_controller.rb
app/controllers/users_controller.rb
=> Fix list of projects in user controller

app/assets/javascripts/app/adwords.js, app/views/juntos_bootstrap/layouts/juntos_bootstrap.html.slim
This pr aim to add Google AdWords.
=> Script AdWords

app/assets/javascripts/app/subgoals.js, app/assets/stylesheets/_headers_from_future_juntos.scss, app/assets/stylesheets/juntos_bootstrap/_main.scss, app/views/juntos_bootstrap/projects/show.html.slim, app/views/juntos_bootstrap/shared/_header_big.html.slim, config/locales/catarse_bootstrap/views/projects/show.en.yml, config/locales/catarse_bootstrap/views/projects/show.pt.yml
This pr aim to add a fixed donate button in campain layout and add a new header for mobile version.
=> Add donate button, mobile header link

app/views/juntos_bootstrap/projects/show.html.slim
This pr aim to add a donate button on mobile
=> Add btn donate on mobile

app/assets/stylesheets/juntos_bootstrap/_main.scss, app/views/juntos_bootstrap/projects/_subgoals_mobile.html.slim, app/views/juntos_bootstrap/projects/show.html.slim, config/locales/catarse_bootstrap/activerecord.en.yml, config/locales/catarse_bootstrap/views/projects/show.en.yml, config/locales/catarse_bootstrap/views/projects/show.pt.yml
This pr aim to solve some issues in campaign layout. 
- The donate button wasn't displayed on mobile.
- The project status was duplicated on mobile.
=> Mobile campaign

app/views/juntos_bootstrap/contributions/_contribution.html.slim, config/locales/catarse_bootstrap/views/projects/contributions.en.yml, config/locales/catarse_bootstrap/views/projects/contributions.pt.yml
This pr aim to hide anonymous supporters name.
=> Hide anonymous supporter name

Gemfile, Gemfile.lock, app/assets/javascripts/app/review_form.js, app/assets/stylesheets/juntos_bootstrap/_colors.sass, app/assets/stylesheets/juntos_bootstrap/_main.scss, app/controllers/countries_controller.rb, app/controllers/projects/contributions_controller.rb, app/views/juntos_bootstrap/projects/contributions/edit.html.slim, app/views/juntos_bootstrap/projects/show.html.slim, config/locales/catarse_bootstrap/activerecord.en.yml, config/locales/catarse_bootstrap/activerecord.pt.yml, config/locales/catarse_bootstrap/views/channels/admin/admin.en.yml, config/locales/catarse_bootstrap/views/projects/contributions.en.yml, config/locales/catarse_bootstrap/views/projects/contributions.pt.yml, config/locales/catarse_bootstrap/views/projects/show.en.yml, config/locales/catarse_bootstrap/views/projects/show.pt.yml, config/routes.rb, db/migrate/20160816182817_add_country_to_contribution.rb, lib/tasks/update_countries_contributions.rake, spec/controllers/countries_controller_spec.rb
Add translations for contribution and add gem to deal with countries translations and states.
=> Add translations for contribution

app/views/juntos_bootstrap/projects/show.html.slim
This pr aim to fix a bug that was happening on IOS.
- The tabs wasn't displayed correctly.
=> Fix tabs on IOS

app/assets/stylesheets/juntos_bootstrap/_main.scss, app/views/juntos_bootstrap/contributions/_contribution.html.slim, app/views/juntos_bootstrap/projects/_subgoals_mobile.html.slim
This pr aim to fix a bug that happened on project stats display.
=> Project stats display

app/assets/stylesheets/juntos_bootstrap/_main.scss, app/views/juntos_bootstrap/projects/_subgoals_mobile.html.slim, app/views/juntos_bootstrap/shared/_header.html.slim
This pr aim to fix the tabs and header on IOS.
=> Inline header and tabs

app/policies/project_policy.rb, spec/controllers/projects_controller_spec.rb
Add new permited_attributes to project_policy
=> Edit online campaign

app/assets/javascripts/app/review_form.js, app/views/catarse_moip/moip/review.html.slim, app/views/juntos_bootstrap/projects/contributions/_recurring_payment.html.slim, config/locales/catarse_bootstrap/views/projects/contributions.en.yml, config/locales/catarse_bootstrap/views/projects/contributions.pt.yml
This pr aim to adjust masks of moip_pagarme form and add i18n
=> Adjust masks of moip_pagarme form and add i18n

app/assets/stylesheets/miv/_main_sidebar.sass, app/views/projects/index.html.slim
This pr aim to remove blog section and change the position of the sidebar items on home page.
=> Home sidebar

app/assets/javascripts/app/masks.js, app/views/juntos_bootstrap/admin/financials/index.html.slim, app/views/juntos_bootstrap/admin/projects/index.html.slim
This pr aim to fix a bug on date mask. Those forms were using, the old mask plugin.
=> Fix admin date mask

app/assets/stylesheets/juntos_bootstrap/_colors.sass, app/assets/stylesheets/juntos_bootstrap/_main.scss, app/assets/stylesheets/juntos_bootstrap/_variables.scss, app/assets/stylesheets/juntos_bootstrap/catarse.css.sass, app/assets/stylesheets/resources/projects/_index.sass, app/assets/stylesheets/resources/static/_partners.sass, app/views/juntos_bootstrap/admin/site_partners/index.html.slim, app/views/projects/index.html.slim, app/views/site_partners/index.html.slim, config/locales/catarse_bootstrap/views/projects/index.pt.yml
This pr aim to add a partner tooltip and add a new admin partner layout
**tooltip**
New layout 
**Before:** 
**After:**
=> Partner tooltip and new admin partner layout

app/assets/stylesheets/juntos_bootstrap/_main.scss, app/controllers/application_controller.rb, app/controllers/channels/base_controller.rb, app/controllers/channels/profiles_controller.rb, app/decorators/channel_decorator.rb, app/models/project_total.rb, app/views/juntos_bootstrap/channels/profiles/show.html.slim, config/locales/catarse_bootstrap/views/channels/profiles/show.en.yml, config/locales/catarse_bootstrap/views/channels/profiles/show.pt.yml, spec/controllers/channels/profiles_controller_spec.rb, spec/decorators/channel_decorator_spec.rb, spec/factories.rb
This pr aim to add a statistics bar to each channel.
=> Add statistics bar to channels

app/views/catarse_moip/moip/_terms.html.slim, config/locales/catarse_bootstrap/views/projects/contributions.en.yml, config/locales/catarse_bootstrap/views/projects/contributions.pt.yml
Add i18n and new paragraph to terms
=> Add i18n and new paragraph to terms

app/models/project.rb, app/models/subscription.rb, db/migrate/20161111163636_create_subscriptions.rb, spec/factories.rb, spec/models/project_spec.rb, spec/models/subscription_spec.rb
This model allows the junto's projects to receive recurring contributions.
=> Create subscription model

app/models/transaction.rb, db/migrate/20161114181417_create_transactions.rb, spec/factories.rb, spec/models/transaction_spec.rb
This model represents every transaction made for a subscription with the pagarme's gem.
=> Create transaction model

Gemfile, Gemfile.lock, app/services/recurring_contribution/pagarme_api.rb, app/services/recurring_contribution/pagarme_subscription.rb, spec/factories.rb, spec/fixtures/vcr_cassettes/recurring_contributions/pagarme/bank_billet_subscription_build.yml, spec/fixtures/vcr_cassettes/recurring_contributions/pagarme/credit_card_subscription_build.yml, spec/services/recurring_contribution/pagarme_subscription_spec.rb, spec/services/recurring_contribution/update_plans_spec.rb, spec/support/recurring_contributions_helper.rb, spec/support/vcr.rb
This service will create the subscriptions on PagarMe's API.
=> Create pagarme's subscription service

app/models/subscription.rb, app/services/recurring_contribution/juntos_subscription.rb, spec/services/recurring_contribution/juntos_subscription_spec.rb, spec/support/recurring_contributions_helper.rb
This service will create the subscription model and its first transaction in the junto's database.
=> Create juntos subscription service

app/assets/javascripts/app/admin-project-form.js, app/assets/javascripts/application.js, app/assets/stylesheets/juntos_bootstrap/_main.scss, app/views/catarse_bootstrap/projects/_dashboard_project.html.slim, app/views/juntos_bootstrap/projects/_dashboard_project.html.slim, app/views/juntos_bootstrap/projects/_dashboard_reward.html.slim, app/views/juntos_bootstrap/projects/_project_basics.html.slim, app/views/juntos_bootstrap/rewards/_form.html.slim
Adjusts in Project review form
Before
After
=> Review form

app/models/project.rb, config/locales/catarse_bootstrap/activerecord.en.yml, config/locales/catarse_bootstrap/activerecord.pt.yml, spec/models/project_spec.rb
about field should have at least one character length validation.
=> Add a minimum length validation for about field on project model

app/decorators/user_decorator.rb
The LazyHelper was delegating the channel call to ApplicationController instead of user.channel
=> Remove LazyHelper from UserDecorator

app/views/juntos_bootstrap/projects/contributions/edit.html.slim
To require the address city field for users accessing the platform from brazil.
=> Update edit form from project contributions

app/assets/javascripts/app/payment.js, app/controllers/projects/contributions_controller.rb, app/views/juntos_bootstrap/projects/contributions/edit.html.slim
When there is preferred_payment_engine set, the preferred payment engine should come selected.
=> list all payment method even if there is preferred_payment_engine

app/controllers/channels/profiles_controller.rb, app/models/contribution.rb, app/models/project.rb, app/queries/channel_statistics_query.rb, app/views/juntos_bootstrap/channels/profiles/show.html.slim, spec/controllers/channels/profiles_controller_spec.rb, spec/queries/channel/statistics_spec.rb
Update Channels:ProfilesController to fetch either successful and online projects for fed the statistics bar.
=> Fetching for successful and online projects in the channel's statistics bar calculations

app/services/recurring_contribution/subscriptions/create.rb, app/services/recurring_contribution/subscriptions/create_pagarme.rb, spec/fixtures/vcr_cassettes/recurring_contributions/pagarme/bank_billet_subscription_build.yml, spec/fixtures/vcr_cassettes/recurring_contributions/pagarme/credit_card.yml, spec/fixtures/vcr_cassettes/recurring_contributions/pagarme/credit_card_subscription_build.yml, spec/services/recurring_contribution/subscriptions/create_pagarme_spec.rb, spec/services/recurring_contribution/subscriptions/create_spec.rb
At the first moment, only a Juntos' subscription will be created and the pagarme subscription will be created only when the scheduled date for its creation was reached.
After this update, all the information needed for subscription creating will be centralized into the juntos' subscriptions gave to this service.
=> Updating RecurringContribution::Subscriptions::Create service

app/controllers/projects/subscriptions_controller.rb, app/policies/subscription_policy.rb, app/services/pagarme/api.rb, app/services/recurring_contribution/subscriptions/cancel_on_pagarme.rb, config/locales/catarse_bootstrap/activerecord.en.yml, config/locales/catarse_bootstrap/activerecord.pt.yml, config/routes.rb, spec/controllers/projects/subscriptions_controller_spec.rb, spec/policies/subscription_policy_spec.rb, spec/services/recurring_contribution/subscriptions/cancel_on_pagarme_spec.rb
This action will be called when a user decides to cancel its subscription.
=> Creating the 'cancel' action on SubscriptionsController

app/models/subscription.rb, app/views/users/_subscriptions.html.slim, spec/models/subscription_spec.rb
The subscriptions with :waiting_for_charging_day are visible too.
=> Updated User's dashboard subscriptions tab

Gemfile, Gemfile.lock, app/assets/stylesheets/juntos_bootstrap/abstract/_fonts.scss, app/assets/stylesheets/juntos_bootstrap/abstract/_variables.scss, app/assets/stylesheets/juntos_bootstrap/catarse.css.scss, app/assets/stylesheets/juntos_bootstrap/components/_cards.scss, app/models/plan.rb, app/views/juntos_bootstrap/projects/contributions/_link_to_new.html.slim, app/views/juntos_bootstrap/projects/plans/_dashboard_project_plans.html.slim, app/views/juntos_bootstrap/projects/show.html.slim, app/views/juntos_bootstrap/projects/subscriptions/new.html.slim, config/locales/catarse_bootstrap/views/projects/contributions.en.yml, config/locales/catarse_bootstrap/views/projects/contributions.pt.yml
Now a warning message is displayed for recurring projects which doesn't contain associated plans:
The sass was downgraded to **version '3.4.5'** because an error was being raised. The explanation can be found [here](https://github.com/sass/sass/issues/1476)
=> Updated projects show view

app/services/recurring_contribution/subscriptions/processor.rb, spec/services/recurring_contribution/subscriptions/processor_spec.rb
Now, the subscription is charged if the charging_day choosed by user is equal to the subscription's creation day.
=> Updated RecurringContribution::Subscriptions::Processor service

app/models/plan.rb, app/services/recurring_contribution/update_plans.rb, spec/factories.rb, spec/services/recurring_contribution/subscriptions/create_spec.rb, spec/services/recurring_contribution/subscriptions/update_juntos_spec.rb, spec/services/recurring_contribution/update_plans_spec.rb, spec/support/recurring_contributions_helper.rb
The project does not work with trial plans. Then, this pr avoids a plan to be persisted if it is a trial one.
=> Skip trial plans from pagarme

app/services/pagarme/api.rb, spec/fixtures/vcr_cassettes/pagarme/credit_card/create.yml, spec/fixtures/vcr_cassettes/pagarme/credit_card/invalid_attributes_error.yml, spec/fixtures/vcr_cassettes/pagarme/plan/find.yml, spec/fixtures/vcr_cassettes/pagarme/plan/invalid_id_error.yml, spec/fixtures/vcr_cassettes/pagarme/subscription/create.yml, spec/fixtures/vcr_cassettes/pagarme/subscription/invalid_attributes_error.yml, spec/fixtures/vcr_cassettes/pagarme/subscription/invalid_id_error.yml, spec/fixtures/vcr_cassettes/pagarme/transaction/invalid_id_error.yml, spec/services/pagarme/api_spec.rb, spec/services/recurring_contribution/subscriptions/create_spec.rb, spec/services/recurring_contribution/subscriptions/update_juntos_spec.rb, spec/services/recurring_contribution/update_plans_spec.rb, spec/support/recurring_contributions_helper.rb, spec/support/shared_examples/pagarme/create_resource.rb, spec/support/shared_examples/pagarme/find_resource.rb
handling PagarMe::RequestError raised when a juntos' model which represents a pagarme resource has a nil model_code.
=> Updated Pagarme::API service

app/decorators/contribution_decorator.rb, app/models/contribution.rb, app/views/juntos_bootstrap/admin/contributions/index.html.slim, config/locales/admin.en.yml, config/locales/admin.pt.yml, spec/decorators/contribution_decorator_spec.rb
including the CPF/CNPJ field to the contributions list table.
=> Updated the admin/contributions view

app/controllers/users/bank_accounts_controller.rb, app/models/attachment.rb, app/models/authorization_document.rb, app/models/bank_account.rb, app/policies/bank_account_policy.rb, config/locales/catarse_bootstrap/activerecord.en.yml, config/locales/catarse_bootstrap/activerecord.pt.yml, config/routes.rb, db/migrate/20170209202100_create_attachments.rb, db/migrate/20170210164706_add_authorized_to_bank_accounts.rb, db/migrate/20170210202355_change_attachments_type_column_name.rb, db/migrate/20170213202254_create_authorization_documents.rb, spec/controllers/users/bank_accounts_controller_spec.rb, spec/models/attachment_spec.rb, spec/models/authorization_document_spec.rb, spec/models/bank_account_spec.rb, spec/policies/bank_account_policy_spec.rb, spec/policies/subscription_policy_spec.rb, spec/support/shared_examples/policies/create_permission.rb, spec/support/shared_examples/policies/permitted_attributes.rb
Some needed changes to accomplish this task:
=> Created the Users::BankAccountsController

Gemfile, Gemfile.lock, app/assets/javascripts/app/project.js, app/assets/javascripts/app/user/bank_account_form.js, app/assets/javascripts/app/user/document_uploader.js, app/assets/stylesheets/juntos_bootstrap/abstract/_variables.scss, app/assets/stylesheets/juntos_bootstrap/components/_forms.scss, app/controllers/projects_controller.rb, app/controllers/users/bank_accounts_controller.rb, app/models/authorization_document.rb, app/models/bank.rb, app/models/bank_account.rb, app/policies/bank_account_policy.rb, app/views/juntos_bootstrap/projects/show.html.slim, app/views/users/bank_accounts/_form.html.slim, app/views/users/bank_accounts/new.html.slim, config/locales/catarse_bootstrap/activerecord.en.yml, config/locales/catarse_bootstrap/activerecord.pt.yml, config/locales/catarse_bootstrap/views/projects/show.en.yml, config/locales/catarse_bootstrap/views/projects/show.pt.yml, config/locales/catarse_bootstrap/views/users/bank_accounts/new.en.yml, config/locales/catarse_bootstrap/views/users/bank_accounts/new.pt.yml, db/migrate/20170215190153_add_description_to_authorization_documents.rb, spec/models/authorization_document_spec.rb, spec/models/bank_account_spec.rb, spec/models/bank_spec.rb, spec/policies/bank_account_policy_spec.rb
This form will be used to add and associate the user's bank account to a recurring project.
**Form appearance**:
=> Created the 'bank_account_form'

app/assets/stylesheets/_headers_from_future_juntos.scss, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/juntos_bootstrap/_main.scss, app/assets/stylesheets/juntos_bootstrap/abstract/_variables.scss, app/assets/stylesheets/juntos_bootstrap/catarse.css.scss, app/assets/stylesheets/juntos_bootstrap/components/_buttons.scss, app/views/juntos_bootstrap/projects/show.html.slim, app/views/juntos_bootstrap/rewards/_form.html.slim
For organization and maintenance purposes, the buttons css styles were moved for the _buttons.scss file.
=> Refactor and move to a single file all the button css definitions

app/assets/javascripts/app/project.js, app/assets/javascripts/app/project/dashboard_documents.js, app/assets/javascripts/lib/subviews_manager.js, app/assets/stylesheets/juntos_bootstrap/_extra.scss, app/assets/stylesheets/juntos_bootstrap/abstract/_fonts.scss, app/assets/stylesheets/juntos_bootstrap/catarse.css.scss, app/assets/stylesheets/juntos_bootstrap/components/_tables.scss, app/assets/stylesheets/juntos_bootstrap/containers/_dashboards.scss, app/views/juntos_bootstrap/projects/_dashboard_documents.html.slim, app/views/juntos_bootstrap/projects/bank_accounts/_associate.html.slim, app/views/juntos_bootstrap/projects/required_documents/_list.html.slim, app/views/juntos_bootstrap/projects/show.html.slim, app/views/users/bank_accounts/_form.html.slim, config/locales/catarse_bootstrap/views/projects/show.en.yml, config/locales/catarse_bootstrap/views/projects/show.pt.yml, config/locales/catarse_bootstrap/views/users/documents/list.en.yml, config/locales/catarse_bootstrap/views/users/documents/list.pt.yml
This view contains both the needed documents for organizations and the organization's bank account information.
**Demonstration**:
=> Created user's documents dashboard on project's profile

app/models/authorization_document.rb, app/models/user.rb, app/models/user_authorization_document.rb, spec/models/user_authorization_document_spec.rb
=> Ignore optional authorization documents only on User's model

app/controllers/projects_controller.rb, app/models/home_banner.rb, app/models/project.rb, app/queries/project/index_scope.rb, app/views/projects/index.html.slim, spec/controllers/projects_controller_spec.rb, spec/factories.rb, spec/models/project_spec.rb, spec/queries/project/index_scope_rspec.rb
Create scopes for catch projects that have no channel and ones that have visible channels only
=> List only projects without channels and ones that has visible channels

app/models/concerns/contribution/payment_engine_handler.rb, spec/models/concerns/contribution/payment_engine_handler_spec.rb
adding the field 'address_complement' on the billing update methods.
=> Updated the contribution's concern PaymentEngineHandler

app/views/juntos_bootstrap/projects/show.html.slim
=> Removed the 'rewards' tab from project profile's dashboard

app/controllers/projects_controller.rb, app/models/project.rb, app/models/subscription.rb, app/models/subscription_report.rb, app/reports/subscription_collection_report.rb, app/services/recurring_contribution/subscriptions/update_juntos.rb, app/views/juntos_bootstrap/projects/_dashboard_reports.html.slim, app/workers/reports/subscription_worker.rb, config/locales/catarse_bootstrap/activerecord.pt.yml, config/locales/catarse_bootstrap/views/projects/show.en.yml, config/locales/catarse_bootstrap/views/projects/show.pt.yml, config/routes.rb, db/migrate/20170314164419_add_confirmed_at_to_subscription.rb, db/migrate/20170317173705_create_subscription_reports.rb, spec/controllers/projects_controller_spec.rb, spec/fixtures/reports/apoiadores.csv, spec/models/subscription_report_spec.rb, spec/reports/subscription_collection_report_spec.rb, spec/services/recurring_contribution/subscriptions/update_juntos_spec.rb, spec/workers/reports/subscription_worker_spec.rb
When a project is recurring, the project's admin should be able to download the subscriptions report.
=> Create report for project subscriptions

app/assets/javascripts/app/payment.js, app/assets/javascripts/app/project_form.js, app/views/catarse_moip/moip/review.html.slim
changing the 'disabled' button's property triggers.
=> Fixed the submit button on contributions and projects forms

app/controllers/projects_controller.rb, app/views/juntos_bootstrap/projects/_dashboard_documents.html.slim, app/views/juntos_bootstrap/projects/show.html.slim
which has a legal_entity as their owner.
=> Enabled the documents tab for all projects

app/assets/stylesheets/_headers_from_future_juntos.scss, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/juntos_bootstrap/abstract/_fonts.scss, app/assets/stylesheets/juntos_bootstrap/abstract/_variables.scss, app/controllers/projects/subscriptions_controller.rb, app/decorators/subscription_decorator.rb, app/views/juntos_bootstrap/projects/subscriptions/show.html.slim, app/views/projects/contributions/show.html.slim, config/locales/catarse_bootstrap/views/projects/subscriptions.en.yml, config/locales/catarse_bootstrap/views/projects/subscriptions.pt.yml, config/routes.rb, spec/controllers/projects/subscriptions_controller_spec.rb, spec/decorators/subscription_decorator_spec.rb, spec/factories.rb
=> Created the donator thanks page for subscriptions

app/decorators/subscription_decorator.rb, app/models/subscription.rb, app/services/recurring_contribution/subscriptions/processor.rb, app/views/juntos_bootstrap/projects/subscriptions/show.html.slim, config/locales/catarse_bootstrap/views/projects/subscriptions.en.yml, config/locales/catarse_bootstrap/views/projects/subscriptions.pt.yml, spec/decorators/subscription_decorator_spec.rb, spec/models/subscription_spec.rb
The user whose have scheduled the subscription(paid with bank billet) for a day different than the day of subscribing will receive a message informing that he will receive the bank  billet link on his e-mail.
=> Fix on donator thanks view

app/views/juntos_bootstrap/projects/_dashboard_reports.html.slim, config/locales/catarse_bootstrap/views/projects/show.en.yml, config/locales/catarse_bootstrap/views/projects/show.pt.yml
adding a link appearance to the subscriptions' report generator.
=> Updated the reports tab on the project profile
