juntos-com-vc/juntos.com.vc

- app/controllers/projects_controller.rb
- app/services/pagarme_service.rb
- app/views/juntos_bootstrap/projects/_project_basics.html.slim
- spec/services/pagarme_service_spec.rb
According to [Pagar.me](https://pagar.me) docs, it's not possible to change the `document_number` option while updating bank account information.
> Add fields to allow the project owner to change bank account information

- app/controllers/projects_controller.rb
- app/services/pagarme_service.rb
- app/views/juntos_bootstrap/projects/_project_basics.html.slim
- app/workers/recipient_worker.rb
- config/locales/catarse_bootstrap/views/projects/show.pt.yml
- db/migrate/20160301184237_add_recipient_job_running_to_projects.rb
- spec/services/pagarme_service_spec.rb
- spec/workers/recipient_worker_spec.rb
To prevent users from sending multiple requests to insert their bank account information, we have to disable those fields and show them a message.
> Disable bank account fields when there is a job running in background

- README.md
It was pointing to an old branch instead of `master`
> Update Coveralls badge on README.md

- app/assets/javascripts/app/project/project_image_uploader.js
- app/models/project.rb
- app/models/project_image.rb
- app/views/juntos_bootstrap/projects/image_thumbs/_gallery_thumb.html.slim
- app/views/juntos_bootstrap/projects/templates/_thumbnail_card_template.html.slim
- app/workers/project_image_process_worker.rb
- spec/factories.rb
- spec/models/project_image_spec.rb
- spec/models/project_spec.rb
- spec/workers/project_image_process_worker_spec.rb
Images images will now be processed by CarrierWave via a Sidekiq worker
in order to avoid timeouts on Heroku; While the image is being processed a
loading gif placeholder will take its place.
> Process images on background to avoid timeouts

- spec/uploaders/project_uploader_spec.rb
The size of project thumbnail was changed on [this commit](https://github.com/juntos-com-vc/juntos.com.vc/commit/db90a66a3f1aa8cffa87008b04ad79c9bb71a1a3) but the spec wasn't updated :disappointed:.
> Fix ProjectUploaderSpec

- app/models/user.rb
- app/services/user/fix_users_documents_url_service.rb
- db/migrate/20160406214956_add_original_documents_url_to_users.rb
- lib/tasks/fix_user_documents_url.rake
- spec/services/user/fix_users_documents_url_service_spec.rb
- spec/tasks/fix_user_documents_url_rake_spec.rb
As we're changing the way user documents are uploaded on the platform
we need to migrate the existing data to a new field wich will stote this data
from now
> Create a task to migrate users documents urls

- config/initializers/s3_direct_upload.rb
An unecessary comma caused an Invalid Policy error while trying to
upload files do Amazon S3.
> Fix typo on S3 Direct Upload configuration

- app/views/juntos_bootstrap/projects/image_thumbs/_gallery_thumb.html.slim
- app/views/juntos_bootstrap/projects/image_thumbs/_partner_thumb.html.slim
Display non-processed (resized) images on project dashboard after saving
changes. Before, it was showing a loading GIF.
> Show original uploaded images on project dashboard

- app/assets/javascripts/app/project/project_cover_uploader.js
On project dashboard, in the cover images section, we should keep the progress bar on page after the upload has been completed.
> Keep the upload progress bar on page

- app/decorators/channel_decorator.rb
- app/models/channel.rb
- app/views/juntos_bootstrap/admin/channels/_form.html.slim
- app/views/juntos_bootstrap/shared/_header_channel.html.slim
- config/locales/catarse_bootstrap/activerecord.pt.yml
- config/locales/catarse_bootstrap/views/layouts/header.pt.yml
- db/migrate/20160412163357_add_custom_submit_text_to_channels.rb
- spec/decorators/channel_decorator_spec.rb
By adding a new field to the database, we're allowing project admins
to modify the "Submit your project" message
> Allow channels to customize submit project message

- app/views/juntos_bootstrap/shared/_header_channel.html.slim
Using `resource` causes an error while rendering a project page (`resource` in this context is the project itself, not the channel).
> [Fix] Custom submit text on channels

- app/decorators/channel_decorator.rb
- spec/decorators/channel_decorator_spec.rb
As the images will be used on e-mails we must pass an absolute url.
> Update email_image method on channel decorator

- app/controllers/reports/contribution_reports_for_project_owners_controller.rb
- spec/controllers/reports/contribution_reports_for_project_owners_controller_spec.rb
When an unauthorized user tries to download a contributions report, the application was just displaying an HTTP 500 error. Now they'll get redirected to the homepage.
> Redirect unauthorized users when trying to download reports

- app/models/project.rb
Esse PR corrige o erro 500 arremessado na rota "/pt/projects?pg_search=quilombo&page=1" que impedia a barra de busca por projeto de funcionar.
> Fix error 500 when sending XHR for project searching

- app/views/juntos_bootstrap/projects/_mobile_video.html.slim
This pr aim to fix project stats layout.
**Context** : The last pull request was merged without all the corrections and a bug happened. A component in project stats was duplicated. This pr aim to solve this problem.
**Before** 
**After**
> Fix project stats layout

- app/controllers/admin/contributions_controller.rb
- app/models/contribution.rb
- app/views/juntos_bootstrap/admin/contributions/index.html.slim
- app/views/juntos_bootstrap/projects/show.html.slim
- app/views/juntos_bootstrap/user_notifier/mailer/contribution_canceled_after_confirmed.html.slim
- config/locales/admin.en.yml
- config/locales/admin.pt.yml
- config/locales/catarse_bootstrap/views/projects/show.en.yml
- config/locales/catarse_bootstrap/views/projects/show.pt.yml
- spec/models/contribution_spec.rb
Wrong company name in email that is sent when contribution is cancelled, add a confirm with "are you sure" message when cancelling a recurring contribution and add filters `only recurring contributions` and `only cancel recurring contributions` in contributions admin.
> Updates in cancel recurring contribution

- app/views/juntos_bootstrap/devise/registrations/new.html.slim
- app/views/juntos_bootstrap/user_notifier/mailer/contribution_canceled_after_confirmed.html.slim
- app/views/juntos_bootstrap/user_notifier/mailer/in_analysis_project_channel.html.slim
- config/locales/catarse_bootstrap/views/devise/registrations/new.en.yml
- config/locales/catarse_bootstrap/views/devise/registrations/new.pt.yml
Context: 
- After a user cancel a contribution, he recives an email. In the message the company_name is wrong, display **Cartase** instead **Juntos com vc**.
- On sign_up page form, when a user click on,  **terms of use and privacy** he is redirect to **Cartase** instead **Juntos com vc**.
> Fix company_name and redirection to catarse

- app/controllers/admin/users_controller.rb
- spec/controllers/admin/users_controller_spec.rb
It fixes the problem on exporting only 25 records in csv file.
> Remove pagination when exporting csv file

- db/migrate/20161004180821_change_project_total_contribution_types.rb
- spec/factories.rb
- spec/models/project_spec.rb
- spec/models/project_total_spec.rb
The project_total.pledge value wasn't according with the expected value because the project_total view was selecting contributions with these states: 'confirmed', 'refunded' and 'requested_refund'. So, the view was replaced for another without the refunded state filter.
Created specs for the new Project#pledged behavior.
Updated specs for the view project_total.
> Fix projects with refunded payments

- app/assets/stylesheets/juntos_bootstrap/_main.scss
- app/controllers/admin/projects_controller.rb
- app/models/project.rb
- app/services/move_project_to_channel.rb
- app/views/juntos_bootstrap/admin/projects/index.html.slim
- config/locales/admin.en.yml
- config/locales/admin.pt.yml
- config/routes.rb
- spec/controllers/admin/projects_controller_spec.rb
- spec/factories.rb
- spec/services/move_project_to_channel_spec.rb
This pr aim to create a new admin form to move a project to a channel.
**Context:** Sometimes a project was created outside a channel accidentally and there was no way to move a project to a channel.
> Move a project to channel

- Gemfile
- Gemfile.lock
- app/models/project.rb
- spec/factories.rb
- spec/models/project_spec.rb
pg_search's gem on 0.7.8 version was throwing an active record error when two scopes made with pg_search_scope method are chained:
```PG::AmbiguousColumn: ERROR:  ORDER BY "pg_search_rank" is ambiguous```
Problem solved on this PR: https://github.com/Casecommons/pg_search/pull/258
pg_search's gem changelog: https://github.com/Casecommons/pg_search/blob/master/CHANGELOG.md#105
The specs for this case(chain pg_search_scope scopes) was created.
> Fix Project's pg_search when used together with user_name_contains

- app/assets/javascripts/app/admin.js
- app/assets/stylesheets/juntos_bootstrap/_main.scss
- app/views/juntos_bootstrap/admin/users/index.html.slim
On admin menu dropdown, after click on dropdown icon, the menu icon was hiding behind the menu and adjust the menu dropdown size.
**Before:** 
**After:**
> Fix dropdown admin

- app/models/contribution.rb
- spec/models/contribution_spec.rb
Chain Contributions#only_cancelled_recurring and Contributions#project_name_contains was raising an ActiveRecord's error, caused by ambiguity between project_id columns.
This PR aims to fix this bug making the correct references to the project_id column.
> Fix bug on the admin contributions view filters

- app/models/user.rb
- app/views/users/_current_user_fields.html.slim
- config/locales/catarse_bootstrap/activerecord.en.yml
- config/locales/catarse_bootstrap/activerecord.pt.yml
- spec/models/user_spec.rb
This bug was about the field chosen to select the staff types of an user, the field is a select field and is difficult to select and deselect options(is needed to press ctrl and stuff like that). It was replaced for checkboxes(more easy to use, especially for multiple choices).
I had a problem with the precheck of these checkboxes - made by the formtastic gem - and needed to replace the User method that fill the checkboxes(staffs_array), now the collection passed to the checkboxes builder method is an array with all the staff ids. This method was replaced by User.staff_description(used to fill the label values).
Check this stackoverflow article:  http://stackoverflow.com/questions/32548540/formtastic-pre-check-few-checkboxes
I decided to use the 'user/staff' name key for …
> Bug when try to remove users from Juntos's team

- app/controllers/admin/projects_controller.rb
- app/views/juntos_bootstrap/admin/projects/index.html.slim
- spec/controllers/admin/projects_controller_spec.rb
- spec/models/project_spec.rb
When user is inside a channel, for example: http://elos.juntos.com.vc and try to filter projects by channel - what doesn't makes sense, because only projects of the channel supposed to be listed - is raised an ActiveRecord's error, caused by an ambiguous column. To solve this, the select field must be disabled when user is inside a channel and the current channel is selected in channel's select field.
> Fix bug on the admin projects view filters

- app/views/catarse_paypal_express/paypal_express/review.html.slim
This pr aim to remove the cpf field from catarse_paypal_express gem
> Remove cpf field from catarse_paypal_express gem

- Gemfile
- Gemfile.lock
- app/models/plan.rb
- config/locales/enumerize.en.yml
- config/locales/enumerize.pt.yml
- db/migrate/20161104164112_create_plans.rb
- spec/factories.rb
- spec/models/plan_spec.rb
Was necessary specify the ```attr_accessible``` in Plan's model([here](https://github.com/juntos-com-vc/juntos.com.vc/pull/241/files#diff-e17c11183d250fb09321ae866bd7a4d9R2)) to avoid the Brakeman's warning: ```Brakeman: Mass Assignment not restricted using attr_accessible```
> Create model for Plans

- app/controllers/application_controller.rb
- app/controllers/concerns/exception_handler.rb
- spec/features/users_spec.rb
The implementation of .xhr?(alias for #xml_http_request?) returns 0 when the request made is an ajax request(check [this](https://github.com/rails/rails/issues/16444)). So the verification in the redirect_user_back_after login was updating the session[:return_to] even for ajax requests. This PR aims to fix this problem.
> Fix after login redirect bug

- app/models/plan.rb
- app/services/recurring_contribution/update_plans.rb
- db/migrate/20161104164112_create_plans.rb
- spec/factories.rb
- spec/models/plan_spec.rb
- spec/services/recurring_contribution/update_plans_spec.rb
This service will synchronize all PagarMe's API Plans made for recurring contributions subscriptions in the application's database.
> Update plans service

- app/models/project.rb
- spec/models/project_spec.rb
It was only possible to filter projects for goal if the user enter both minimum and maximum goal values.
Now it is possible to filter projects for minimum, maximum or both goal values.
> Fixed project goal searching

- app/models/project.rb
- app/views/catarse_bootstrap/projects/show.html.slim
- app/views/juntos_bootstrap/projects/_project_basics.html.slim
- app/views/juntos_bootstrap/projects/show.html.slim
- config/locales/catarse_bootstrap/views/projects/show.en.yml
- config/locales/catarse_bootstrap/views/projects/show.pt.yml
- db/migrate/20161109220349_add_available_for_contribution_flag_for_project.rb
- spec/factories.rb
- spec/models/project_spec.rb
* The flag indicates if the project is available for online contributions.
* If so, the `Support Project` button is visible for the users.
* The admin user may manage the project contribution availability on the `about` tab.
> added available_for_contribution flag to project

- db/migrate/20161123210302_change_can_cancel_function_to4_days_for_slip.rb
- spec/models/contribution_spec.rb
When contribution `created_at` is older than 4 days, it should be canceled even if it is slip payment method.
> updated the function that checks if the contribution is expired

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/services/project/create.rb
- app/services/project/crud.rb
- app/services/project/update.rb
- app/views/juntos_bootstrap/projects/_project_basics.html.slim
- app/views/juntos_bootstrap/projects/new.html.slim
- config/locales/catarse_bootstrap/activerecord.en.yml
- config/locales/catarse_bootstrap/activerecord.pt.yml
- config/locales/catarse_bootstrap/simple_form.en.yml
- config/locales/catarse_bootstrap/simple_form.pt.yml
- spec/controllers/projects_controller_spec.rb
- spec/models/project_spec.rb
- spec/services/project/create_spec.rb
- spec/services/project/update_spec.rb
- spec/support/shared_examples/project_admin_crud_services/crud_service.rb
Juntos' admins must have permission to create or update projects with values greater than 60 for the ```online_days``` attribute.
> Updating the online_days project attribute validations

- app/services/recurring_contribution/subscriptions/update_status.rb
- spec/services/recurring_contribution/subscriptions/update_status_spec.rb
This service will be responsible for update juntos' subscriptions statuses when the PagarMe's API sinalize(via POST request) some change in the subscription status.
> Creating service which will update juntos subscription status 

- app/controllers/projects/reminders_controller.rb
- app/services/project/reminder_service.rb
- app/views/juntos_bootstrap/projects/_project_about.html.slim
- app/views/juntos_bootstrap/projects/_project_remind_me.html.slim
- app/workers/reminder_project_worker.rb
- config/locales/catarse_bootstrap/views/projects/show.en.yml
- config/locales/catarse_bootstrap/views/projects/show.pt.yml
- spec/controllers/projects/reminders_controller_spec.rb
- spec/services/project/reminder_service_spec.rb
It was showing `remind me` link even when the `project.expires_at` was `nil`. It was causing error, because the reminders_controller did not check it and just did `project.expires_at - 48.hours`.
Now the `remind me` link is not even shown if `project.expires_at` is `nil`.
> Remove remind me for no expires at project

- app/assets/stylesheets/_headers_from_future_juntos.scss
- app/views/juntos_bootstrap/projects/_dashboard_reward.html.slim
- app/views/juntos_bootstrap/rewards/_form.html.slim
- config/locales/catarse_bootstrap/simple_form.en.yml
- config/locales/catarse_bootstrap/simple_form.pt.yml
All juntos project's buttons have the yellow as main color. Following some UX purposes, the color of the edit and destroy buttons of the rewards form was changed to blue and red.
This PR contains a change that should has been made [here](https://github.com/juntos-com-vc/juntos.com.vc/pull/249)
Before:
After:
> Changing the edit/destroy rewards buttons to the right color 

- app/controllers/subscriptions_controller.rb
- app/services/pagarme/api.rb
- app/services/recurring_contribution/subscriptions/create_pagarme.rb
- app/services/recurring_contribution/subscriptions/update_status.rb
- config/routes.rb
- spec/controllers/subscriptions_controller_spec.rb
- spec/services/recurring_contribution/subscriptions/update_status_spec.rb
This endpoint will be called by PagarMe(via POST request) when a change on subscription's status occurs, updating the Juntos' Subscription to the new status.
> Creating subscriptions post back endpoint

- app/controllers/projects/posts_controller.rb
- app/controllers/projects_controller.rb
- spec/controllers/projects/posts_controller_spec.rb
- spec/controllers/projects_controller_spec.rb
**Problem:**
When creating a project post, there is no `current_user` sending into params, what is causing error because the post belongs to user.
**Solution:**
Use an existing protected method that merges the project params to current user.
> fix the way that the project params is sent to update service

- app/views/juntos_bootstrap/projects/_project_header.html.slim
The project contributions count is calculated in two different places, where in one of them only the `status: 'confirmed', 'requested_refund'` matter, while in the other one the `status: 'confirmed', 'requested_refund', 'refunded'` matter.
This let the project contributions count for both being calculated in the same place.
> Fix inconsistence on display project contributions

- app/models/subscription.rb
- app/services/pagarme/api.rb
- app/services/recurring_contribution/subscriptions/create_juntos.rb
- db/migrate/20161223191639_add_charging_day_to_subscriptions.rb
- db/migrate/20161223194522_add_credit_card_key_to_subscriptions.rb
- spec/factories.rb
- spec/models/subscription_spec.rb
- spec/services/recurring_contribution/subscriptions/create_juntos_spec.rb
This service will create a subscription on juntos' database, scheduling the pagarme's charging day. All subscriptions which have the `waiting_for_charging_day` status will be created on pagarme if the current day was equal to the `charging_day` attribute.
Two more attributes were added on Subscription's model: `charging_day` and `credit_card_key`. The `credit_card_key` is a reference to the CreditCard created on Pagarme when a subscription paid with credit card is made. The `charging day` refer to the month's day which the user will be charged by pagarme.
> Creating RecurringContribution::Subscriptions::CreateJuntos service

- app/models/contribution.rb
- lib/tasks/cron.rake
- spec/models/contribution_spec.rb
When a contribution has the state `waiting_confirmation` for 5 or more days, it should be canceled.
> Update how many days a waiting confirmation contribution should be canceled

- app/models/subscription.rb
- app/models/transaction.rb
- app/workers/recurring_contribution/charging_subscription_worker.rb
- lib/tasks/cron.rake
- spec/factories.rb
- spec/models/subscription_spec.rb
- spec/models/transaction_spec.rb
- spec/services/recurring_contribution/subscriptions/create_juntos_spec.rb
- spec/services/recurring_contribution/subscriptions/update_juntos_spec.rb
- spec/support/shared_examples/recurring_contributions/update_status_services.rb
- spec/tasks/recurring_contribution/create_scheduled_pagarme_subscriptions_rake_spec.rb
- spec/workers/recurring_contribution/charging_subscription_worker_spec.rb
This rake task calls the RecurringContribution::ChargingSubscriptionWorker which will search for all juntos subscriptions with the `waiting_for_charging_day` status and then call the RecurringContribution::Subscriptions::Create service passing each juntos's subscription found. This way, all the scheduled subscriptions will be created on the Pagarme's database.
> Creating the charging subscriptions rake task

- spec/controllers/admin/projects_controller_spec.rb
- spec/models/contribution_spec.rb
- spec/models/recurring_contribution_spec.rb
Some assertions are making the build fail sporadically. It is because the array order matter in those assertions, when it should not.
> Refactor the specs that are making the build fail sporadically

- Gemfile
- Gemfile.lock
- app/controllers/admin/channels_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/rewards_controller.rb
- app/controllers/users_controller.rb
- app/models/authorization.rb
- app/models/channels_subscriber.rb
- app/models/contribution.rb
- app/models/contribution_report.rb
- app/models/user.rb
- app/services/project/crud.rb
- config/application.rb
- spec/controllers/admin/channels_controller_spec.rb
- spec/models/channel_spec.rb
- spec/services/project/update_spec.rb
When updating to rails 4, this gem was added to avoid removing `attr_accessible` and `attr_protected` methods from models.
It removes to use rails 4+ `strong_paramteres` intead
> Remove `protected_attributes` gem and using rails strong_parameters instead

- app/assets/javascripts/app/project.js
- app/assets/stylesheets/juntos_bootstrap/_colors.sass
- app/assets/stylesheets/juntos_bootstrap/_main.scss
- app/models/plan.rb
- app/models/project.rb
- app/policies/project_policy.rb
- app/views/juntos_bootstrap/projects/_dashboard_project_plans.html.slim
- app/views/juntos_bootstrap/projects/show.html.slim
- config/locales/catarse_bootstrap/activerecord.en.yml
- config/locales/catarse_bootstrap/activerecord.pt.yml
- config/locales/catarse_bootstrap/views/projects/show.en.yml
- config/locales/catarse_bootstrap/views/projects/show.pt.yml
- db/migrate/20170102211454_create_projects_plans.rb
- spec/factories.rb
- spec/models/plan_spec.rb
- spec/models/project_spec.rb
This tab allows the project owner and/or an admin user associates plans to their projects.
> Adding the plans tab in the project's dashboard

- app/controllers/projects_controller.rb
- app/decorators/project_decorator.rb
- app/models/project.rb
- app/policies/project_policy.rb
- app/views/juntos_bootstrap/projects/_dashboard_project.html.slim
- app/views/juntos_bootstrap/projects/_project_basics.html.slim
- spec/controllers/projects_controller_spec.rb
- spec/decorators/project_decorator_spec.rb
- spec/models/project_spec.rb
- spec/models/user_spec.rb
- spec/policies/project_policy_spec.rb
When the project is visible to users (project state is online, successful...), some attributes should no longer be able to be editable by non-admin users.
> Update project edit rules

- app/controllers/subgoals_controller.rb
- app/views/juntos_bootstrap/subgoals/index.html.slim
- config/routes.rb
- spec/controllers/subgoals_controller_spec.rb
Permit subgoal attributes from subgoal policy permitted_attributes.
Remove the unused subgoals index route, because it was accessed when forbidden attributes error was raised and caused error.
> Fix subgoal forbidden attributes by permitting attributes using the policy gem

- app/controllers/admin/projects_controller.rb
- spec/controllers/admin/projects_controller_spec.rb
This action was created because some views called by this controller use the `best_in_place` gem to update the project resource. But, there is no endpoint to process this kind of action, therefore, the update not occurs.
> Created the 'update' action on Admin::ProjectsController

- app/models/subscription.rb
- app/policies/subscription_policy.rb
- app/views/juntos_bootstrap/projects/subscriptions/new.html.slim
- config/locales/catarse_bootstrap/activerecord.en.yml
- config/locales/catarse_bootstrap/activerecord.pt.yml
- spec/models/subscription_spec.rb
- spec/policies/subscription_policy_spec.rb
When the user creates a new subscription, he will have predefined values for the charges number of his subscription.  Avoiding subscriptions with only one charge, for example.
> Added predefined values for subscription charges

- app/services/pagarme/api.rb
- app/services/recurring_contribution/update_plans.rb
- app/workers/recurring_contribution/update_plans_worker.rb
- lib/tasks/cron.rake
- spec/tasks/recurring_contribution/create_scheduled_pagarme_subscriptions_rake_spec.rb
- spec/workers/recurring_contribution/update_plans_worker_spec.rb
The `recurring_contribution:plans:update` will synchronizes pagarme's plans on juntos' database and the `recurring_contribution:subscriptions:cancel_expired` will searches for expired subscriptions and cancel them.
> Created 'subscriptions:cancel_expired' and 'plans:update' rake tasks

- app/controllers/admin/channels_controller.rb
- app/controllers/projects_controller.rb
- app/models/channel.rb
- app/views/juntos_bootstrap/admin/channels/_form.html.slim
- config/locales/catarse_bootstrap/simple_form.en.yml
- config/locales/catarse_bootstrap/simple_form.pt.yml
- config/locales/catarse_bootstrap/views/admin/channels.en.yml
- config/locales/catarse_bootstrap/views/admin/channels.pt.yml
- db/migrate/20170123192632_add_visible_to_channels.rb
- spec/factories.rb
- spec/models/channel_spec.rb
Some channels should not be visible on the channels' menu on the root page of application after its creation. So, was added the `visible` attribute to the channels table, which will decide if a channel will be visible or not.
> Creating the Channels visibility feature

- app/controllers/transactions_controller.rb
- app/services/pagarme/api.rb
- app/services/recurring_contribution/transactions/find_or_create.rb
- spec/services/recurring_contribution/transactions/find_or_create_spec.rb
- spec/support/recurring_contributions_helper.rb
When the `Pagarme's postback` response tries to update a transaction that is not on `Juntos' database`, it was crashing.
This pr implements a service to check if the transaction is persisted on `Juntos' database`. If so, then update. If not, create it from `Pagarme`.
> Create a service to fetch or create transaction from postback

- app/views/juntos_bootstrap/user_notifier/mailer/in_analysis_project.html.slim
This pr removes the deadline for project to be analyzed from the email sent.
Now, the email's body just tells the project is going to be analyzed as soon as possible instead.
> Update the email template sent when a project is sent to in_analysis

- app/observers/contribution_observer.rb
- spec/factories.rb
- spec/observers/contribution_observer_spec.rb
When the contribution is canceled, the office is notified that a confirmed contribution was canceled, even when the contribution was pending or waiting_confirmation
> Remove alias that sends wrong template email when the contribution is canceled

- app/controllers/channels/profiles_controller.rb
- app/views/juntos_bootstrap/channels/profiles/edit.html.slim
- config/locales/catarse_bootstrap/views/channels/profiles/edit.en.yml
- config/locales/catarse_bootstrap/views/channels/profiles/edit.pt.yml
- spec/controllers/channels/profiles_controller_spec.rb
The inherited_resource's gem `update!` method was removed and replaced by a straight call of the active record's `update` method.
> Fixed Channels::ProfilesController update action

- app/assets/javascripts/app/review_form.js
The payer name and payer email going to MoIP as parameters were got from `current_user`, even if the user set a different one when filling the contribution payment data form.
> Send payer name and payer email when contributing

- app/controllers/admin/channels_controller.rb
- app/models/channel.rb
- app/views/juntos_bootstrap/admin/channels/_form.html.slim
- config/locales/admin.en.yml
- config/locales/admin.pt.yml
- spec/controllers/admin/channels_controller_spec.rb
- spec/factories.rb
- spec/models/channel_spec.rb
When updating a channel, it should not allow to set recurring to false if the channel is recurring and it has projects associated.
> Disable edit recurring channel

- lib/tasks/deploy.rake
The duplicated heroku keyword was removed from the restart app subtask.
> Updated deploy rake task

- app/policies/project_policy.rb
- app/views/juntos_bootstrap/projects/_dashboard_project.html.slim
- app/views/juntos_bootstrap/projects/_project_basics.html.slim
- spec/controllers/projects_controller_spec.rb
- spec/policies/project_policy_spec.rb
If the current user is a project owner and the project went online already, it should be able to edit everything from 'projects' tab and the name only from 'basics' tab.
> Allow project owner to be able to edit name in 'basics' tab and everything in 'project' tab

- app/assets/stylesheets/juntos_bootstrap/_main.scss
The problem is that on the project-progress-description div, it was set word-wrap to allow unbreakable words to be broken. It was breaking a number that should not be broken.
> Add `word-wrap: normal;` to the mobile project progress description

- spec/decorators/project_decorator_spec.rb
The `#time_to_go` method makes a time calculation and wasn't freezing the base time. So there was an inconsistency with the expected method result.
> Fix build error caused by the ProjectDecoratorSpec

- app/models/authorization_document.rb
- app/models/user.rb
- app/models/user_authorization_document.rb
- spec/factories.rb
- spec/models/user_authorization_document_spec.rb
The user model has a special condition for the authorization documents' validation. Three of the document categories needed by user are optional, so, if a save/update request is sent to user with empty attachment urls for these categories the operation must be valid.
> Ignore optional authorization documents only on User's model

- app/assets/javascripts/app/form/remote_requests.js
- app/assets/javascripts/app/project/authorization_documents_management.js
- app/assets/javascripts/app/project/bank_account_management.js
- app/assets/javascripts/app/user/authorization_documents_form.js
- app/assets/stylesheets/juntos_bootstrap/_main.scss
- app/assets/stylesheets/juntos_bootstrap/catarse.css.scss
- app/assets/stylesheets/juntos_bootstrap/components/_links.scss
- app/assets/stylesheets/juntos_bootstrap/components/_tables.scss
- app/assets/stylesheets/juntos_bootstrap/containers/_dashboards.scss
- app/decorators/authorization_document_decorator.rb
- app/models/authorization_document.rb
- app/view_objects/project_documentation_view_object.rb
- app/views/juntos_bootstrap/projects/_dashboard_documents.html.slim
- app/views/juntos_bootstrap/projects/bank_accounts/_associate.html.slim
- app/views/juntos_bootstrap/projects/required_documents/_list.html.slim
- app/views/juntos_bootstrap/projects/show.html.slim
- app/views/users/authorization_documents/_form.html.slim
- config/locales/catarse_bootstrap/views/users/documents/list.en.yml
- config/locales/catarse_bootstrap/views/users/documents/list.pt.yml
- config/locales/catarse_bootstrap/views/users/documents/new.en.yml
- config/locales/catarse_bootstrap/views/users/documents/new.pt.yml
- spec/decorators/authorization_document_decorator_spec.rb
- spec/factories.rb
- spec/models/authorization_document_spec.rb
- spec/view_objects/project_documentation_view_object_spec.rb
To give a better feedback to the user, the list of authorization documents is shown on documents tab. Also highlighting the status of each document, whether sent or not.
It is possible to visualize the sent documents clicking on the icon near of the status.
**Demonstration**:
> Showing the user documents on project profile's documents tab

- app/controllers/projects_controller.rb
The project's recipient account validation was removed from the 'send_to_analysis' action.
> Removing 'recurring contribution' legacy code from ProjectsController

- app/assets/javascripts/app/project/bank_account_management.js
- app/assets/stylesheets/juntos_bootstrap/_main.scss
- app/assets/stylesheets/juntos_bootstrap/abstract/_fonts.scss
- app/assets/stylesheets/juntos_bootstrap/components/_cards.scss
- app/decorators/bank_account_decorator.rb
- app/decorators/project_decorator.rb
- app/view_objects/project_documentation_view_object.rb
- app/views/juntos_bootstrap/projects/bank_accounts/_associate.html.slim
- app/views/juntos_bootstrap/projects/bank_accounts/_associated_account.html.slim
- config/locales/catarse_bootstrap/activerecord.en.yml
- config/locales/catarse_bootstrap/activerecord.pt.yml
- config/locales/catarse_bootstrap/views/users/bank_accounts/management.en.yml
- config/locales/catarse_bootstrap/views/users/bank_accounts/management.pt.yml
- db/migrate/20170314173224_add_default_value_to_account_digit.rb
- spec/decorators/bank_account_decorator_spec.rb
- spec/view_objects/project_documentation_view_object_spec.rb
When a project already has an associated bank account, the account details must be shown on the bank account's tab:
> Showing the associated bank account on project's profile documents tab

- app/controllers/channels/profiles_controller.rb
- app/services/channel/recurring_channel_first_time_checker.rb
- spec/controllers/channels/profiles_controller_spec.rb
- spec/services/channels/recurring_channel_first_time_checker_spec.rb
Was added a hook on the Channel::ProfilesController which redirects users who doesn't have recurring projects for the page of the recurring channel policies, to give a explanation about how this kind of channel works.
> Showing the recurring channel's policies for new users

- app/controllers/projects_controller.rb
- app/models/plan.rb
- db/migrate/20170317123241_add_active_to_plans.rb
- spec/factories.rb
- spec/models/plan_spec.rb
Filling the lack of the Pagarme's API which doesn't permit delete actions even if the model doesn't have registered associations on the database.
> Allowed the deactivation of recurring plans

- app/assets/javascripts/app/project/bank_account_management.js
- app/assets/stylesheets/juntos_bootstrap/_main.scss
- app/views/juntos_bootstrap/projects/bank_accounts/_associate.html.slim
Now, either the '+' icon or the button itself trigger the event.
> Fixed the 'new bank account' button on project's documents tab

- app/models/channel.rb
- app/views/juntos_bootstrap/admin/channels/index.html.slim
The problem is that even if a channel has no category, on index action it tries to call channel.category.name, causing then an error.
> Fix nil pointer exception on admin channels index

- app/decorators/user_decorator.rb
- app/models/user.rb
- app/views/juntos_bootstrap/projects/show.html.slim
- config/locales/catarse_bootstrap/views/projects/show.en.yml
- config/locales/catarse_bootstrap/views/projects/show.pt.yml
- spec/decorators/user_decorator_spec.rb
- spec/factories.rb
- spec/models/user_spec.rb
The `.pending_documents?` user's method now is checking if all the required documents were sent by the legal entity.
> Adding a validation for the Legal Entity's authorization documents

- app/models/project.rb
- app/models/subscription.rb
- app/queries/project/subscriptions_pledged_value_query.rb
- spec/factories.rb
- spec/models/project_spec.rb
- spec/models/subscription_spec.rb
- spec/queries/project/subscriptions_pledged_value_query_spec.rb
The Project's `.pledged` method used to calculate only the value coming from contributions, but recurring projects use subscriptions as the donation's mechanism.
This PR aims to calculate this new kind of donation type and show the value at the project profile.
> Enabling the pledged value's calculation for recurring projects

- app/controllers/projects/subscriptions_controller.rb
- spec/controllers/projects/subscriptions_controller_spec.rb
When creating a subscription, the `channel` variable should be initialized, because the form behaves differently when it's a recurring channel
> Initialize `channel` variable when new subscription is rendered

- app/views/juntos_bootstrap/projects/subscriptions/new.html.slim
The form was moved to the left side of the screen.
> Updated the subscription's 'new' view

- app/controllers/projects_controller.rb
- app/decorators/project_decorator.rb
- app/models/project.rb
- app/views/juntos_bootstrap/projects/show.html.slim
- spec/decorators/project_decorator_spec.rb
- spec/models/project_spec.rb
When the project is linked to a channel, it should use the channel's main color as default. If it's empty or the project has no channel, use the project's color instead.
> Let the project to use the channel's color as default when it is set

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/user.rb
- app/views/juntos_bootstrap/projects/contributions/_contribution.html.slim
- app/views/juntos_bootstrap/projects/contributions/_pending.html.slim
- app/views/juntos_bootstrap/projects/show.html.slim
- app/views/juntos_bootstrap/projects/supporters/_card.html.slim
- app/views/juntos_bootstrap/projects/supporters/_list.html.slim
- config/locales/catarse_bootstrap/views/projects/show.en.yml
- config/locales/catarse_bootstrap/views/projects/show.pt.yml
- spec/factories.rb
- spec/models/project_spec.rb
- spec/models/user_spec.rb
The donators count was still based exclusively on the Contribution model. So, when some user make a subscription for a recurring project, this donation is not count. Now, the project's method `.total_contributions` searches for users with paid transactions when the project is recurring.
> Fixed the donators count on recurring projects' profile page

- app/models/subscription.rb
- app/services/recurring_contribution/subscriptions/update_juntos.rb
- app/services/recurring_contribution/transactions/find_or_create.rb
- db/migrate/20170405192543_add_bank_billet_url_to_transactions.rb
- db/migrate/20170405193817_add_current_to_transactions.rb
- spec/models/subscription_spec.rb
- spec/services/recurring_contribution/subscriptions/update_juntos_spec.rb
- spec/services/recurring_contribution/transactions/find_or_create_spec.rb
- spec/support/recurring_contributions_helper.rb
Now, when a subscription is created with the bank billet payment method, the url for the bank billet generated by pagarme is saved on the transaction model.
> Saving the bank billet url for subscriptions paid with bank billet

- app/models/subscription.rb
- spec/models/subscription_spec.rb
When the contribution is being created using English as language, the `cpf` field should allow blank. When the contribution is being created using Portuguese as language, the `cpf` field should not allow blank.
> Allow nil for cpf field for non-Brazilians

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/subscription.rb
- app/models/user.rb
- app/queries/project/subscriptions_pledged_value_query.rb
- spec/controllers/projects_controller_spec.rb
- spec/models/project_spec.rb
- spec/models/subscription_spec.rb
- spec/models/user_spec.rb
- spec/queries/project/subscriptions_pledged_value_query_spec.rb
It does not need to display the hole pledged value for recurring projects. The pledged value should only be calculated for the current month.
> Calculate the recurring project's pledged value using the paid subscriptions for the current month only

- app/views/juntos_bootstrap/projects/subscriptions/new.html.slim
- config/locales/catarse_bootstrap/views/projects/subscriptions.en.yml
- config/locales/catarse_bootstrap/views/projects/subscriptions.pt.yml
adding an observation on the form's cpf field, remembering foreign users that this field is required only for Brazilians.
> Updated the 'subscriptions/new' view

- spec/services/recurring_contribution/subscriptions/processor_spec.rb
- spec/support/shared_examples/recurring_contributions/subscriptions_processor.rb
When the subscription's charging day is the same than the current day, the tests are creating the subscription on PagarMe instead of scheduling it.
This pr stubs the subscription's charge_scheduled_for_today? to return false when the subscription should be scheduled.
> Fix tests failure when the current day is the same than subscription's charging day
